# Site settings
title: Washington Trail Runs
email: scott@washingtontrailruns.com 
baseurl: "/WashingtonTrailRunsBlog" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: scottcha 
github_username:  scottcha

# Build settings
markdown: kramdown
